exclude: '^$|.idea|venv|settings|scripts'
fail_fast: false
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'
    hooks:
      -   id: autopep8

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      -   id: remove-crlf
      -   id: remove-tabs
