"""Add Verification code column

Revision ID: 23aeb0d3e090
Revises: 25aa6d0954cb
Create Date: 2023-11-24 03:02:28.052749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23aeb0d3e090'
down_revision = '25aa6d0954cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code',
                  sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###
