"""moved to cases. drop new requests and current req

Revision ID: 25aa6d0954cb
Revises: a2a95012073c
Create Date: 2023-11-09 18:39:44.347237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models import PacketReturnStatus, Decision

# revision identifiers, used by Alembic.
revision = '25aa6d0954cb'
down_revision = 'a2a95012073c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('num_of_children', sa.Integer(), nullable=False),
    sa.Column('outreach_date', sa.Date(), nullable=False),
    sa.Column('packet_return_status', sa.Enum(PacketReturnStatus), server_default=PacketReturnStatus.WAITING.name, nullable=False),
    sa.Column('packet_received_date', sa.Date(), nullable=True),
    sa.Column('staff_initials', sa.String(length=80), nullable=True),
    sa.Column('decision', sa.Enum(Decision), server_default=Decision.WAITING.name, nullable=False),
    sa.Column('num_children_enrolled', sa.Integer(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('not_enrolled_reason', sa.String(length=80), nullable=True),
    sa.Column('assigned_to_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', name='_customer_id_uc')
    )
    op.drop_table('new_requests')
    op.drop_table('current_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('num_of_children', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('outreach_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('packet_return_status', sa.Enum('RETURNED', 'NOT_RETURNED', 'WAITING', name='packetreturnstatus'), nullable=False),
    sa.Column('packet_received_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('staff_initials', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('decision', sa.Enum(Decision), server_default=str(Decision.WAITING), nullable=False),
    sa.Column('num_children_enrolled', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('decision_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('not_enrolled_reason', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='current_requests_pkey')
    )
    op.create_table('new_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('num_of_children', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('outreach_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='new_requests_pkey'),
    sa.UniqueConstraint('customer_id', name='new_requests_customer_id_key')
    )
    op.drop_table('cases')
    # ### end Alembic commands ###
