"""Update users table with auth fields

Revision ID: 2e9168e291dc
Revises: eb806419d8dd
Create Date: 2023-09-26 10:29:59.388668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9168e291dc'
down_revision = 'eb806419d8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verified_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'verified_on')
    op.drop_column('users', 'modified_on')
    op.drop_column('users', 'created_on')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
