"""Create current requests table

Revision ID: 68045196ba42
Revises: 04fd691b3547
Create Date: 2023-10-04 17:35:06.747175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68045196ba42'
down_revision = '04fd691b3547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('num_of_children', sa.Integer(), nullable=False),
    sa.Column('outreach_date', sa.Date(), nullable=False),
    sa.Column('packet_return_status', sa.Enum('RETURNED', 'NOT_RETURNED', 'WAITING', name='packetreturnstatus'), nullable=False),
    sa.Column('packet_received_date', sa.Date(), nullable=True),
    sa.Column('staff_initials', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.Enum('ENROLLED', 'NOT_ENROLLED', 'WAITING', name='decision'), nullable=False),
    sa.Column('num_children_enrolled', sa.Integer(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('not_enrolled_reason', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_requests')
    # ### end Alembic commands ###
