"""update customer id fields

Revision ID: a2a95012073c
Revises: 68045196ba42
Create Date: 2023-10-13 14:59:48.882282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a95012073c'
down_revision = '68045196ba42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'new_requests', ['customer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'new_requests', type_='unique')
    # ### end Alembic commands ###
