name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox tox-gh-actions
      - run: tox -eflake8
      - run: tox -edocs

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./
      - name: Run unit tests with code coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage report -m --fail-under=90
        working-directory: ./
      - name: Run behave tests
        run: |
          behave
        working-directory: ./
